//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Transfer_File {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DataSet1")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataSet1 : global::System.Data.DataSet {
        
        private T30DataTable tableT30;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public DataSet1() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected DataSet1(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["T30"] != null)) {
                    base.Tables.Add(new T30DataTable(ds.Tables["T30"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public T30DataTable T30 {
            get {
                return this.tableT30;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["T30"] != null)) {
                    base.Tables.Add(new T30DataTable(ds.Tables["T30"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableT30 = ((T30DataTable)(base.Tables["T30"]));
            if ((initTable == true)) {
                if ((this.tableT30 != null)) {
                    this.tableT30.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSet1.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableT30 = new T30DataTable();
            base.Tables.Add(this.tableT30);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializeT30() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DataSet1 ds = new DataSet1();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void T30RowChangeEventHandler(object sender, T30RowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class T30DataTable : global::System.Data.TypedTableBase<T30Row> {
            
            private global::System.Data.DataColumn _columnSTOCK_NO;
            
            private global::System.Data.DataColumn _columnBULL_PRICE;
            
            private global::System.Data.DataColumn _columnLDC_PRICE;
            
            private global::System.Data.DataColumn _columnBEAR_PRICE;
            
            private global::System.Data.DataColumn _columnLAST_MTH_DATE;
            
            private global::System.Data.DataColumn columnSETTYPE;
            
            private global::System.Data.DataColumn _columnMARK_W;
            
            private global::System.Data.DataColumn _columnMARK_P;
            
            private global::System.Data.DataColumn _columnMARK_L;
            
            private global::System.Data.DataColumn _columnIND_CODE;
            
            private global::System.Data.DataColumn _columnSTK_CODE;
            
            private global::System.Data.DataColumn _columnMARK_M;
            
            private global::System.Data.DataColumn _columnSTOCK_NAME;
            
            private global::System.Data.DataColumn _columnMATCH_INTERNAL;
            
            private global::System.Data.DataColumn _columnORDER_LIMIT;
            
            private global::System.Data.DataColumn _columnORDERS_LIMIT;
            
            private global::System.Data.DataColumn _columnPREPAY_RATE;
            
            private global::System.Data.DataColumn _columnMARK_S;
            
            private global::System.Data.DataColumn _columnMARK_F;
            
            private global::System.Data.DataColumn _columnMARK_DAY_TRADE;
            
            private global::System.Data.DataColumn _columnSTK_CTGCD;
            
            private global::System.Data.DataColumn columnFILLER;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public T30DataTable() {
                this.TableName = "T30";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal T30DataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected T30DataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _STOCK_NOColumn {
                get {
                    return this._columnSTOCK_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _BULL_PRICEColumn {
                get {
                    return this._columnBULL_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _LDC_PRICEColumn {
                get {
                    return this._columnLDC_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _BEAR_PRICEColumn {
                get {
                    return this._columnBEAR_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _LAST_MTH_DATEColumn {
                get {
                    return this._columnLAST_MTH_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SETTYPEColumn {
                get {
                    return this.columnSETTYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _MARK_WColumn {
                get {
                    return this._columnMARK_W;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _MARK_PColumn {
                get {
                    return this._columnMARK_P;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _MARK_LColumn {
                get {
                    return this._columnMARK_L;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _IND_CODEColumn {
                get {
                    return this._columnIND_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _STK_CODEColumn {
                get {
                    return this._columnSTK_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _MARK_MColumn {
                get {
                    return this._columnMARK_M;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _STOCK_NAMEColumn {
                get {
                    return this._columnSTOCK_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _MATCH_INTERNALColumn {
                get {
                    return this._columnMATCH_INTERNAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _ORDER_LIMITColumn {
                get {
                    return this._columnORDER_LIMIT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _ORDERS_LIMITColumn {
                get {
                    return this._columnORDERS_LIMIT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _PREPAY_RATEColumn {
                get {
                    return this._columnPREPAY_RATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _MARK_SColumn {
                get {
                    return this._columnMARK_S;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _MARK_FColumn {
                get {
                    return this._columnMARK_F;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _MARK_DAY_TRADEColumn {
                get {
                    return this._columnMARK_DAY_TRADE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn _STK_CTGCDColumn {
                get {
                    return this._columnSTK_CTGCD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn FILLERColumn {
                get {
                    return this.columnFILLER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public T30Row this[int index] {
                get {
                    return ((T30Row)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event T30RowChangeEventHandler T30RowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event T30RowChangeEventHandler T30RowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event T30RowChangeEventHandler T30RowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event T30RowChangeEventHandler T30RowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddT30Row(T30Row row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public T30Row AddT30Row(
                        string _STOCK_NO, 
                        string _BULL_PRICE, 
                        string _LDC_PRICE, 
                        string _BEAR_PRICE, 
                        string _LAST_MTH_DATE, 
                        string SETTYPE, 
                        string _MARK_W, 
                        string _MARK_P, 
                        string _MARK_L, 
                        string _IND_CODE, 
                        string _STK_CODE, 
                        string _MARK_M, 
                        string _STOCK_NAME, 
                        string _MATCH_INTERNAL, 
                        string _ORDER_LIMIT, 
                        string _ORDERS_LIMIT, 
                        string _PREPAY_RATE, 
                        string _MARK_S, 
                        string _MARK_F, 
                        string _MARK_DAY_TRADE, 
                        string _STK_CTGCD, 
                        string FILLER) {
                T30Row rowT30Row = ((T30Row)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        _STOCK_NO,
                        _BULL_PRICE,
                        _LDC_PRICE,
                        _BEAR_PRICE,
                        _LAST_MTH_DATE,
                        SETTYPE,
                        _MARK_W,
                        _MARK_P,
                        _MARK_L,
                        _IND_CODE,
                        _STK_CODE,
                        _MARK_M,
                        _STOCK_NAME,
                        _MATCH_INTERNAL,
                        _ORDER_LIMIT,
                        _ORDERS_LIMIT,
                        _PREPAY_RATE,
                        _MARK_S,
                        _MARK_F,
                        _MARK_DAY_TRADE,
                        _STK_CTGCD,
                        FILLER};
                rowT30Row.ItemArray = columnValuesArray;
                this.Rows.Add(rowT30Row);
                return rowT30Row;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                T30DataTable cln = ((T30DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new T30DataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this._columnSTOCK_NO = base.Columns["STOCK-NO"];
                this._columnBULL_PRICE = base.Columns["BULL-PRICE"];
                this._columnLDC_PRICE = base.Columns["LDC-PRICE"];
                this._columnBEAR_PRICE = base.Columns["BEAR-PRICE"];
                this._columnLAST_MTH_DATE = base.Columns["LAST-MTH-DATE"];
                this.columnSETTYPE = base.Columns["SETTYPE"];
                this._columnMARK_W = base.Columns["MARK-W"];
                this._columnMARK_P = base.Columns["MARK-P"];
                this._columnMARK_L = base.Columns["MARK-L"];
                this._columnIND_CODE = base.Columns["IND-CODE"];
                this._columnSTK_CODE = base.Columns["STK-CODE"];
                this._columnMARK_M = base.Columns["MARK-M"];
                this._columnSTOCK_NAME = base.Columns["STOCK-NAME"];
                this._columnMATCH_INTERNAL = base.Columns["MATCH-INTERNAL"];
                this._columnORDER_LIMIT = base.Columns["ORDER-LIMIT"];
                this._columnORDERS_LIMIT = base.Columns["ORDERS-LIMIT"];
                this._columnPREPAY_RATE = base.Columns["PREPAY-RATE"];
                this._columnMARK_S = base.Columns["MARK-S"];
                this._columnMARK_F = base.Columns["MARK-F"];
                this._columnMARK_DAY_TRADE = base.Columns["MARK-DAY-TRADE"];
                this._columnSTK_CTGCD = base.Columns["STK-CTGCD"];
                this.columnFILLER = base.Columns["FILLER"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this._columnSTOCK_NO = new global::System.Data.DataColumn("STOCK-NO", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnSTOCK_NO.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnSTOCK_NO");
                this._columnSTOCK_NO.ExtendedProperties.Add("Generator_UserColumnName", "STOCK-NO");
                base.Columns.Add(this._columnSTOCK_NO);
                this._columnBULL_PRICE = new global::System.Data.DataColumn("BULL-PRICE", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnBULL_PRICE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnBULL_PRICE");
                this._columnBULL_PRICE.ExtendedProperties.Add("Generator_UserColumnName", "BULL-PRICE");
                base.Columns.Add(this._columnBULL_PRICE);
                this._columnLDC_PRICE = new global::System.Data.DataColumn("LDC-PRICE", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnLDC_PRICE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnLDC_PRICE");
                this._columnLDC_PRICE.ExtendedProperties.Add("Generator_UserColumnName", "LDC-PRICE");
                base.Columns.Add(this._columnLDC_PRICE);
                this._columnBEAR_PRICE = new global::System.Data.DataColumn("BEAR-PRICE", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnBEAR_PRICE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnBEAR_PRICE");
                this._columnBEAR_PRICE.ExtendedProperties.Add("Generator_UserColumnName", "BEAR-PRICE");
                base.Columns.Add(this._columnBEAR_PRICE);
                this._columnLAST_MTH_DATE = new global::System.Data.DataColumn("LAST-MTH-DATE", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnLAST_MTH_DATE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnLAST_MTH_DATE");
                this._columnLAST_MTH_DATE.ExtendedProperties.Add("Generator_UserColumnName", "LAST-MTH-DATE");
                base.Columns.Add(this._columnLAST_MTH_DATE);
                this.columnSETTYPE = new global::System.Data.DataColumn("SETTYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSETTYPE);
                this._columnMARK_W = new global::System.Data.DataColumn("MARK-W", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnMARK_W.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnMARK_W");
                this._columnMARK_W.ExtendedProperties.Add("Generator_UserColumnName", "MARK-W");
                base.Columns.Add(this._columnMARK_W);
                this._columnMARK_P = new global::System.Data.DataColumn("MARK-P", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnMARK_P.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnMARK_P");
                this._columnMARK_P.ExtendedProperties.Add("Generator_UserColumnName", "MARK-P");
                base.Columns.Add(this._columnMARK_P);
                this._columnMARK_L = new global::System.Data.DataColumn("MARK-L", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnMARK_L.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnMARK_L");
                this._columnMARK_L.ExtendedProperties.Add("Generator_UserColumnName", "MARK-L");
                base.Columns.Add(this._columnMARK_L);
                this._columnIND_CODE = new global::System.Data.DataColumn("IND-CODE", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnIND_CODE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnIND_CODE");
                this._columnIND_CODE.ExtendedProperties.Add("Generator_UserColumnName", "IND-CODE");
                base.Columns.Add(this._columnIND_CODE);
                this._columnSTK_CODE = new global::System.Data.DataColumn("STK-CODE", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnSTK_CODE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnSTK_CODE");
                this._columnSTK_CODE.ExtendedProperties.Add("Generator_UserColumnName", "STK-CODE");
                base.Columns.Add(this._columnSTK_CODE);
                this._columnMARK_M = new global::System.Data.DataColumn("MARK-M", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnMARK_M.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnMARK_M");
                this._columnMARK_M.ExtendedProperties.Add("Generator_UserColumnName", "MARK-M");
                base.Columns.Add(this._columnMARK_M);
                this._columnSTOCK_NAME = new global::System.Data.DataColumn("STOCK-NAME", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnSTOCK_NAME.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnSTOCK_NAME");
                this._columnSTOCK_NAME.ExtendedProperties.Add("Generator_UserColumnName", "STOCK-NAME");
                base.Columns.Add(this._columnSTOCK_NAME);
                this._columnMATCH_INTERNAL = new global::System.Data.DataColumn("MATCH-INTERNAL", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnMATCH_INTERNAL.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnMATCH_INTERNAL");
                this._columnMATCH_INTERNAL.ExtendedProperties.Add("Generator_UserColumnName", "MATCH-INTERNAL");
                base.Columns.Add(this._columnMATCH_INTERNAL);
                this._columnORDER_LIMIT = new global::System.Data.DataColumn("ORDER-LIMIT", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnORDER_LIMIT.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnORDER_LIMIT");
                this._columnORDER_LIMIT.ExtendedProperties.Add("Generator_UserColumnName", "ORDER-LIMIT");
                base.Columns.Add(this._columnORDER_LIMIT);
                this._columnORDERS_LIMIT = new global::System.Data.DataColumn("ORDERS-LIMIT", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnORDERS_LIMIT.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnORDERS_LIMIT");
                this._columnORDERS_LIMIT.ExtendedProperties.Add("Generator_UserColumnName", "ORDERS-LIMIT");
                base.Columns.Add(this._columnORDERS_LIMIT);
                this._columnPREPAY_RATE = new global::System.Data.DataColumn("PREPAY-RATE", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnPREPAY_RATE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnPREPAY_RATE");
                this._columnPREPAY_RATE.ExtendedProperties.Add("Generator_UserColumnName", "PREPAY-RATE");
                base.Columns.Add(this._columnPREPAY_RATE);
                this._columnMARK_S = new global::System.Data.DataColumn("MARK-S", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnMARK_S.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnMARK_S");
                this._columnMARK_S.ExtendedProperties.Add("Generator_UserColumnName", "MARK-S");
                base.Columns.Add(this._columnMARK_S);
                this._columnMARK_F = new global::System.Data.DataColumn("MARK-F", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnMARK_F.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnMARK_F");
                this._columnMARK_F.ExtendedProperties.Add("Generator_UserColumnName", "MARK-F");
                base.Columns.Add(this._columnMARK_F);
                this._columnMARK_DAY_TRADE = new global::System.Data.DataColumn("MARK-DAY-TRADE", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnMARK_DAY_TRADE.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnMARK_DAY_TRADE");
                this._columnMARK_DAY_TRADE.ExtendedProperties.Add("Generator_UserColumnName", "MARK-DAY-TRADE");
                base.Columns.Add(this._columnMARK_DAY_TRADE);
                this._columnSTK_CTGCD = new global::System.Data.DataColumn("STK-CTGCD", typeof(string), null, global::System.Data.MappingType.Element);
                this._columnSTK_CTGCD.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnSTK_CTGCD");
                this._columnSTK_CTGCD.ExtendedProperties.Add("Generator_UserColumnName", "STK-CTGCD");
                base.Columns.Add(this._columnSTK_CTGCD);
                this.columnFILLER = new global::System.Data.DataColumn("FILLER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFILLER);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public T30Row NewT30Row() {
                return ((T30Row)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new T30Row(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(T30Row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.T30RowChanged != null)) {
                    this.T30RowChanged(this, new T30RowChangeEvent(((T30Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.T30RowChanging != null)) {
                    this.T30RowChanging(this, new T30RowChangeEvent(((T30Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.T30RowDeleted != null)) {
                    this.T30RowDeleted(this, new T30RowChangeEvent(((T30Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.T30RowDeleting != null)) {
                    this.T30RowDeleting(this, new T30RowChangeEvent(((T30Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveT30Row(T30Row row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSet1 ds = new DataSet1();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "T30DataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class T30Row : global::System.Data.DataRow {
            
            private T30DataTable tableT30;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal T30Row(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableT30 = ((T30DataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _STOCK_NO {
                get {
                    try {
                        return ((string)(this[this.tableT30._STOCK_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'STOCK-NO\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._STOCK_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _BULL_PRICE {
                get {
                    try {
                        return ((string)(this[this.tableT30._BULL_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'BULL-PRICE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._BULL_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _LDC_PRICE {
                get {
                    try {
                        return ((string)(this[this.tableT30._LDC_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'LDC-PRICE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._LDC_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _BEAR_PRICE {
                get {
                    try {
                        return ((string)(this[this.tableT30._BEAR_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'BEAR-PRICE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._BEAR_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _LAST_MTH_DATE {
                get {
                    try {
                        return ((string)(this[this.tableT30._LAST_MTH_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'LAST-MTH-DATE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._LAST_MTH_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SETTYPE {
                get {
                    try {
                        return ((string)(this[this.tableT30.SETTYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'SETTYPE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30.SETTYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _MARK_W {
                get {
                    try {
                        return ((string)(this[this.tableT30._MARK_WColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'MARK-W\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._MARK_WColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _MARK_P {
                get {
                    try {
                        return ((string)(this[this.tableT30._MARK_PColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'MARK-P\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._MARK_PColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _MARK_L {
                get {
                    try {
                        return ((string)(this[this.tableT30._MARK_LColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'MARK-L\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._MARK_LColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _IND_CODE {
                get {
                    try {
                        return ((string)(this[this.tableT30._IND_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'IND-CODE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._IND_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _STK_CODE {
                get {
                    try {
                        return ((string)(this[this.tableT30._STK_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'STK-CODE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._STK_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _MARK_M {
                get {
                    try {
                        return ((string)(this[this.tableT30._MARK_MColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'MARK-M\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._MARK_MColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _STOCK_NAME {
                get {
                    try {
                        return ((string)(this[this.tableT30._STOCK_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'STOCK-NAME\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._STOCK_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _MATCH_INTERNAL {
                get {
                    try {
                        return ((string)(this[this.tableT30._MATCH_INTERNALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'MATCH-INTERNAL\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._MATCH_INTERNALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _ORDER_LIMIT {
                get {
                    try {
                        return ((string)(this[this.tableT30._ORDER_LIMITColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'ORDER-LIMIT\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._ORDER_LIMITColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _ORDERS_LIMIT {
                get {
                    try {
                        return ((string)(this[this.tableT30._ORDERS_LIMITColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'ORDERS-LIMIT\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._ORDERS_LIMITColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _PREPAY_RATE {
                get {
                    try {
                        return ((string)(this[this.tableT30._PREPAY_RATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'PREPAY-RATE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._PREPAY_RATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _MARK_S {
                get {
                    try {
                        return ((string)(this[this.tableT30._MARK_SColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'MARK-S\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._MARK_SColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _MARK_F {
                get {
                    try {
                        return ((string)(this[this.tableT30._MARK_FColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'MARK-F\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._MARK_FColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _MARK_DAY_TRADE {
                get {
                    try {
                        return ((string)(this[this.tableT30._MARK_DAY_TRADEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'MARK-DAY-TRADE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._MARK_DAY_TRADEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string _STK_CTGCD {
                get {
                    try {
                        return ((string)(this[this.tableT30._STK_CTGCDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'STK-CTGCD\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30._STK_CTGCDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string FILLER {
                get {
                    try {
                        return ((string)(this[this.tableT30.FILLERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'T30\' 中資料行 \'FILLER\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableT30.FILLERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_STOCK_NONull() {
                return this.IsNull(this.tableT30._STOCK_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_STOCK_NONull() {
                this[this.tableT30._STOCK_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_BULL_PRICENull() {
                return this.IsNull(this.tableT30._BULL_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_BULL_PRICENull() {
                this[this.tableT30._BULL_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_LDC_PRICENull() {
                return this.IsNull(this.tableT30._LDC_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_LDC_PRICENull() {
                this[this.tableT30._LDC_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_BEAR_PRICENull() {
                return this.IsNull(this.tableT30._BEAR_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_BEAR_PRICENull() {
                this[this.tableT30._BEAR_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_LAST_MTH_DATENull() {
                return this.IsNull(this.tableT30._LAST_MTH_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_LAST_MTH_DATENull() {
                this[this.tableT30._LAST_MTH_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSETTYPENull() {
                return this.IsNull(this.tableT30.SETTYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSETTYPENull() {
                this[this.tableT30.SETTYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_MARK_WNull() {
                return this.IsNull(this.tableT30._MARK_WColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_MARK_WNull() {
                this[this.tableT30._MARK_WColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_MARK_PNull() {
                return this.IsNull(this.tableT30._MARK_PColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_MARK_PNull() {
                this[this.tableT30._MARK_PColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_MARK_LNull() {
                return this.IsNull(this.tableT30._MARK_LColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_MARK_LNull() {
                this[this.tableT30._MARK_LColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_IND_CODENull() {
                return this.IsNull(this.tableT30._IND_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_IND_CODENull() {
                this[this.tableT30._IND_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_STK_CODENull() {
                return this.IsNull(this.tableT30._STK_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_STK_CODENull() {
                this[this.tableT30._STK_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_MARK_MNull() {
                return this.IsNull(this.tableT30._MARK_MColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_MARK_MNull() {
                this[this.tableT30._MARK_MColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_STOCK_NAMENull() {
                return this.IsNull(this.tableT30._STOCK_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_STOCK_NAMENull() {
                this[this.tableT30._STOCK_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_MATCH_INTERNALNull() {
                return this.IsNull(this.tableT30._MATCH_INTERNALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_MATCH_INTERNALNull() {
                this[this.tableT30._MATCH_INTERNALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_ORDER_LIMITNull() {
                return this.IsNull(this.tableT30._ORDER_LIMITColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_ORDER_LIMITNull() {
                this[this.tableT30._ORDER_LIMITColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_ORDERS_LIMITNull() {
                return this.IsNull(this.tableT30._ORDERS_LIMITColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_ORDERS_LIMITNull() {
                this[this.tableT30._ORDERS_LIMITColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_PREPAY_RATENull() {
                return this.IsNull(this.tableT30._PREPAY_RATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_PREPAY_RATENull() {
                this[this.tableT30._PREPAY_RATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_MARK_SNull() {
                return this.IsNull(this.tableT30._MARK_SColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_MARK_SNull() {
                this[this.tableT30._MARK_SColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_MARK_FNull() {
                return this.IsNull(this.tableT30._MARK_FColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_MARK_FNull() {
                this[this.tableT30._MARK_FColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_MARK_DAY_TRADENull() {
                return this.IsNull(this.tableT30._MARK_DAY_TRADEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_MARK_DAY_TRADENull() {
                this[this.tableT30._MARK_DAY_TRADEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool Is_STK_CTGCDNull() {
                return this.IsNull(this.tableT30._STK_CTGCDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void Set_STK_CTGCDNull() {
                this[this.tableT30._STK_CTGCDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsFILLERNull() {
                return this.IsNull(this.tableT30.FILLERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetFILLERNull() {
                this[this.tableT30.FILLERColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class T30RowChangeEvent : global::System.EventArgs {
            
            private T30Row eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public T30RowChangeEvent(T30Row row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public T30Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591